#!/bin/bash

if test "x$1" = "x"
then
	example="examples/myRenderObject_6093.js"
else
	example="$1"
fi

java -cp build/libs/grabcraft-litematic-1.16.2-fabric0.17.2-1.1.3-dev.jar:\
/home/gbl/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.8.0/c4ba5371a29ac9b2ad6129b1d39ea38750043eff/gson-2.8.0.jar:\
/home/gbl/.gradle/caches/fabric-loom/1.16.2-mapped-net.fabricmc.yarn-1.16.2+build.1-v2/minecraft-1.16.2-mapped-net.fabricmc.yarn-1.16.2+build.1-v2.jar:\
/home/gbl/.gradle/caches/modules-2/files-2.1/it.unimi.dsi/fastutil/8.2.1/5ad88f325e424f8dbc2be5459e21ea5cab3864e9/fastutil-8.2.1.jar:\
/home/gbl/SoftwareProjects/MyProjects/MinecraftPlugins/libraries/spigot-1.16.3.jar  de.guntram.mcmod.GrabcraftLitematic.Main $example
